### ISSUE TITLE
Geonetwork Postgres upgrade to Geonetwork 4

### ISSUE THREAD

**Issue by srafay** [geonetwork/docker-geonetwork#129]
Hi there, 

Are there any plans to upgrade `geonetwork:3-postgres` to `geonetwork:4-postgres`?

If not soon, is there any guide for upgrading `geonetwork:3-postgres` to `geonetwork:4`.

Thanks

**Comment by juanluisrp** [comment]
There isn't need for `geonetwork:4-postgres`. You can use `geonetwork:4` with these environment variables:
```yaml
environment:
  GEONETWORK_DB_TYPE: postgres
  GEONETWORK_DB_HOST: database
  GEONETWORK_DB_PORT: 5432
  GEONETWORK_DB_NAME: geonetwork
  GEONETWORK_DB_USERNAME: geonetwork
  GEONETWORK_DB_PASSWORD: geonetwork
```
