### ISSUE TITLE
Connect image to elastic

### ISSUE THREAD

**Issue by pvgenuchten** [geonetwork/docker-geonetwork#31]
From next major update Elastic will be essential component of GN, currently is optional, although offers nice extra capabilities. Would be interesting to add environment variables that connect geonetwork to an external (or orchestrated) elastic instance.

**Comment by juanluisrp** [comment]
You can use these variables to set up the Elasticsearch connection:
```yml
      ES_HOST: elasticsearch
      ES_PROTOCOL: http
      ES_PORT: 9200
      ES_USERNAME: es_user
      ES_PASSWORD: es_password

      KB_URL: http://kibana:5601
```
