### ISSUE TITLE
SQLException 'Authentication type 10 is not supported' when connecting to kartoza/postgis image

### ISSUE THREAD

**Issue by benjaminh** [geonetwork/docker-geonetwork#67]
I try to create a docker composition so that geonetwork and geoserver connect to the same Postgres/PostGIS database.
So I use `geonetwork:postgres` image as suggested in the doc to connect to a postgres docker container.

When starting the containers, I get several SQLException errors, and all of them end with: 

```
Initialization of bean failed; nested exception is java.lang.RuntimeException: 
java.sql.SQLException: Cannot create PoolableConnectionFactory
(The authentication type 10 is not supported. Check that you have configured the pg_hba.conf file to include the client's IP address or subnet, and that it is using an authentication scheme supported by the driver.)
```

Here is my `docker-compose.yml` v3.1 example file (without the geoserver container) so that you can reproduce the problem :

```
version: '3.1'

services:

  geonetwork:
    image: geonetwork:postgres
    restart: always
    ports:
      - 8080:8080
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; sh /entrypoint.sh catalina.sh run'
    environment:
      DATA_DIR: /var/lib/geonetwork_data
      POSTGRES_DB_HOST: db
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_NAME: ${POSTGRES_GN_DB}
      POSTGRES_DB_USERNAME: ${POSTGRES_USER}
      POSTGRES_DB_PASSWORD: ${POSTGRES_PASS}
    volumes:
      - geonetwork:/var/lib/geonetwork_data

  db:
    image: kartoza/postgis:13.0
    volumes:
      - geo-db-data:/var/lib/postgresql
    ports:
      - "25434:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
    restart: on-failure
    healthcheck:
      test: "exit 0"

volumes:
  geonetwork:
  geoserver-data:
  geo-db-data:
```

Notes:
- Environment variables are set in a `.env` file, but you can specify your own values.
- The database image is `kartoza/postgis:13.0` because it is the one suggested by the geoserver docker documentation.

By the way, if I try to set a database service with a different image (like `postgis/postgis`), everything works fine. Yet, both images set up a postgres v13.0 database with a postgis v3.0.
I guess this is a matter of postgres configuration, with some differences between the images, but I don't know which ones.

Could you elaborate on what postgres/postgis versions are compatible with the geonetwork docker images, and maybe specify this in the documentation ?
